// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuon__FqucUPS0RkQWMWTZ_Kjg7EXOsb8',
    appId: '1:272628448720:web:d2a1b1dddb3e30f959cdd5',
    messagingSenderId: '272628448720',
    projectId: 'flutterproject-e6ee9',
    authDomain: 'flutterproject-e6ee9.firebaseapp.com',
    storageBucket: 'flutterproject-e6ee9.firebasestorage.app',
    measurementId: 'G-97M3ZLS588',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwsGC4Ru4XJnzYhN2pywko4kh3sPyb7X8',
    appId: '1:272628448720:android:7f9afd41347f095859cdd5',
    messagingSenderId: '272628448720',
    projectId: 'flutterproject-e6ee9',
    storageBucket: 'flutterproject-e6ee9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpcb7vR5BOi43CxjclFYWspihtOT_qa1A',
    appId: '1:272628448720:ios:ed9c69578e9cf8de59cdd5',
    messagingSenderId: '272628448720',
    projectId: 'flutterproject-e6ee9',
    storageBucket: 'flutterproject-e6ee9.firebasestorage.app',
    iosBundleId: 'com.example.firstFlutterProject',
  );
}
